### ISSUE TITLE
Allow use a diferent directory for the files.

### ISSUE THREAD

**Issue by omar10594** [kelvinhokk/cordova-plugin-localization-strings#13]
What if someone have a i18n directory where store translations, and want use that directory for the localization string too.

I think, this plugin should allow users choose where store that files (optional of course).

**Comment by AbhishekJoshi** [comment]
I made a PR with this as we faced the same problem:

**Comment by kelvinhokk** [comment]
Been busy of late.  Could someone help test and report if it works?

**Comment by rodrigograca31** [comment]
@omar10594 maybe this comes too late but PR #22 does that...

As you say some people already have a i18n directory, even though I think we can't use it because this plugin requires an `app` key with the translations inside....

Please give us your thoughts in PR #22

**Comment by rodrigograca31** [comment]
closing since it was implmented
