### ISSUE TITLE
Can I use this plugin for my Cordova app using html, javascript and jquery mobile ?

### ISSUE THREAD

**Issue by hugo4le** [kelvinhokk/cordova-plugin-localization-strings#15]
Hi Kelvinhokk,
Before digging into your plugin. Could you please kindly answer my dump question since I am novice?
Thanks.

**Comment by hugo4le** [comment]
Hi Kelvinhokk,
Before digging into your plugin. Could you please kindly answer my dump question since I am novice?
Thanks.

**Comment by kelvinhokk** [comment]
Hi hugo4le,

You will still need a javascript localisation framework like i18next for your jquery mobile application.

https://github.com/i18next/jquery-i18next

This plugin does not help you on the JS layer, but on the native layer like interfacing with push notifications or other plugins that need localisation like native camera or location prompts.

**Comment by hugo4le** [comment]
Hi Kelvinhokk,
Thank you for the quick respond. Really appreciated it.
So, if I only want to localize app name's language (for instance with iOS, app name language for iTunes App Store for search  and App Icon for display) can I use your plugin?

**Comment by kelvinhokk** [comment]
You may use it to localize app name,  localizing the icon is not supported in this plugin.

**Comment by hugo4le** [comment]
Hi Kelvinhokk,
Thanks a lot!
