### ISSUE TITLE
`cordova prepare` does not run after_prepare if hook is in platform element

### ISSUE THREAD

**Issue by ippeiukai** [kelvinhokk/cordova-plugin-localization-strings#17]
After cloning our repository, we run `cordova prepare`.
With after_prepare hooks in platform element of plugin.xml, this does not work because it only gets triggered by platform specified calls (e.g. `cordova prepare ios`).

FYR there was similar issue with another project: https://github.com/akofman/cordova-plugin-add-swift-support/issues/3#issuecomment-224596597

**Comment by kelvinhokk** [comment]
Thanks for the pull request,  will give it a run through to do a quick test before merging later.

**Comment by kelvinhokk** [comment]
This has been pull and merged into master
