### ISSUE TITLE
[Question] Xcode needs to be configured separately?

### ISSUE THREAD

**Issue by gorzny** [kelvinhokk/cordova-plugin-localization-strings#2]
Hello, 

Is there an assumption that some of the Localization files need to be configured manually, other than what is mentioned in the Readme? Or additional Xcode configuration before or after this plugin is installed?

I'm getting an error on `cordove platform add ios`

<img width="461" alt="screen shot 2017-04-11 at 4 53 03 pm" src="https://cloud.githubusercontent.com/assets/5174587/24930413/6ba088f0-1ed7-11e7-8fd7-6cf9f136c7e2.png">

Thanks for any help.
-Andrew

**Comment by kelvinhokk** [comment]
Hi Andrew, did you try installing the plugin via the --fetch like

cordova plugin add https://github.com/kelvinhokk/cordova-plugin-localization-strings.git --fetch

Alternatively, you can try the latest cordova 6.5.0 which already has the dependency for node-xcode 0.9.0 built in.
