### ISSUE TITLE
Support for Cordova Tools 8.0.0 and Cordova Android 7.0.0

### ISSUE THREAD

**Issue by CoDanny** [kelvinhokk/cordova-plugin-localization-strings#21]
This plugin needs the same changes as here: https://github.com/akofman/cordova-plugin-add-swift-support/pull/45/files

**Comment by zyniq82** [comment]
I think this issue can be closed now, given what was merged in pull request #19 (although that hasn't been released on NPM yet).

**Comment by Tronix117** [comment]
If it's not released on NPM I don't think it should be merged. Default path for a developper having something not working is to quickly check issues. And this one has the information to install it directly from the git and not from NPM.

@kelvinhokk should publish it though.

**Comment by kelvinhokk** [comment]
sorry been busy of late. i have published pull request 19 into npm
