### ISSUE TITLE
Plugin cannot find config.xml

### ISSUE THREAD

**Issue by kustolovic** [kelvinhokk/cordova-plugin-localization-strings#27]
I had a bug resulting in the following message when building/prepare the app:

Error: ENOENT: no such file or directory, open 'config.xml'

It appears that my old app doesn't have config.xml in the root folder but in the www, which is cordova-compatible:

> For projects created with the Cordova CLI (described in The Command-Line Interface), this > file can be found in the top-level directory:

> app/config.xml

> Note that before version 3.3.1-0.2.0, the file existed at app/www/config.xml, and that having > it here is still supported.

It should be good to either support the two locations, or adding a line in the docs asking for having config.xml in the root.

**Comment by rodrigograca31** [comment]
I personally disagree...
IMHO `config.xml` should only exist in the `app/config.xml`

I know the latest docs say its still supported but cordova 3.3.1 has 5+ years.... 2014.... we got to move on.......

**Comment by rodrigograca31** [comment]
Almost 2 years have passed so Im guessing we moved on...
