### ISSUE TITLE
Build on android fails (Premature EOF)

### ISSUE THREAD

**Issue by rubenanton90** [kelvinhokk/cordova-plugin-localization-strings#29]
Installed plugin and deps through _cordova plugin add https://github.com/kelvinhokk/cordova-plugin-localization-strings.git --fetch_

On Android via cordova prepare, cordova complains with the following error
**%My project name%\res\values-es\strings.xml:1:1: Error: Premature end of file**

tried removing and adding android platform. The problem seemed to have disappeared, but resurfaced again after a couple of builds. Any thoughts?

**Comment by rodrigograca31** [comment]
Not sure.... are maybe post the file here....?

Also update the plugin since it has had some updates.
Let use know if the issue still persists, if not please close the issue.

**Comment by rodrigograca31** [comment]
closing due to old age.
