### ISSUE TITLE
Support localising of config.xml permission strings

### ISSUE THREAD

**Issue by pke** [kelvinhokk/cordova-plugin-localization-strings#3]
`NSLocationWhenInUseUsageDescription`
`NSLocationAlwaysUsageDescription`
`NSCameraUsageDescription`
etc

should also be localised. 

So instead of automatic detecting of what needs to go into `InfoPlist.strings` I'd suggest to have 2 translation files for each language, one for `config.json` and one for `app.json`. Everything from `config.json` goes into `InfoPlist.strings`.

What do you think?

**Comment by AndreasGassmann** [comment]
I'm facing the exact same issue.

Another way would be to modify the existing json like that:

    {
      "app": {
        "myString": "Translation"
      },
      "config": {
        "NSCameraUsageDescription": "Take pictures"
      }
    }

Any thoughts on this?

**Comment by kelvinhokk** [comment]
I just updated the plugin, would you like to give 0.1.4 a spin?

**Comment by kelvinhokk** [comment]
Good point there.  i have unpublished 0.1.4 and bumped the version to 1.0.0

**Comment by pke** [comment]
@kelvinhokk Haven't had time to check it out yet. Will report back here. @AndreasGassmann did you check it?

**Comment by kelvinhokk** [comment]
I've been using 1.0.1 for my project, and it seems to work ok so far.  Closing this issue for now.
