### ISSUE TITLE
Use this plugin to localize html files?

### ISSUE THREAD

**Issue by emir-drustinac** [kelvinhokk/cordova-plugin-localization-strings#30]
Can this plugin be used to localize "strings" in html files? If yes, how should it be done?
For example: i have an app and want to let the user change the language in the app. 

I've tried something like this, but it doesnt work:
de.json
{
  ...
  "app" : {
    "btn_login": "Einloggen"
  }
}

en.json
{
  ...
  "app" : {
    "btn_login": "Login"
  }
}

login.html
...
`<button id="btn_login">btn_login</button>`

**Comment by rodrigograca31** [comment]
No, this plugin doesnt do that.
Its from the native translation files, not HTML, use i18n
https://angular.io/guide/i18n
