### ISSUE TITLE
Plugin does not properly respect project file cache

### ISSUE THREAD

**Issue by oliversalzburg** [kelvinhokk/cordova-plugin-localization-strings#33]
Cordova caches previously read project files. So any changes made by this plugin are lost when another plugin also modifies the iOS project. As this plugin modifies the project in a non-standard manner.

To fix this, the project file has to be evicted from the cache after writing it. I'm still working on the details in [our fork](https://github.com/fairmanager-cordova/plugin-localization-strings/blob/dev/scripts/create_ios_strings.js#L151).

**Comment by Fender123** [comment]
could you please add a pull request fixing this issue in this pluging?

**Comment by rodrigograca31** [comment]
@Fender123 is this still an issue? caching.......? :thinking: 
can anyone link to some documentation about this? Thanks!

**Comment by Fender123** [comment]
yes absolutely. But it depends on some settings. It is only an issue if the xcode project file is changed in multiple scripts. In my case it is cordova-ios itself because I am setting SwiftVersion preference. Which seems to be using a cached version of the project.pbxproj file and is therefore lacking the changes made by this plugin.

**Comment by rodrigograca31** [comment]
Unfortunately I'm not familiar with iOS so cant help much. :cry:

**Comment by Fender123** [comment]
@oliversalzburg fix (https://github.com/fairmanager-cordova/plugin-localization-strings/blob/dev/hooks/createIosStrings.js#L157-L161) solves the issue for me. But his fork moved in another direction and differs from this project. Even the hook filenames were changed.

**Comment by oliversalzburg** [comment]
Sorry. This ship has sailed.

**Comment by rodrigograca31** [comment]
@oliversalzburg according with @Fender123 it has not, so I think I will reopen the issue....

@Fender123 seems those lines could be implemented here:
https://github.com/kelvinhokk/cordova-plugin-localization-strings/blob/master/scripts/create_ios_strings.js#L151

if you dont mint please fork it or try it somehow and report back. We would appreciate a PR!

**Comment by oliversalzburg** [comment]
Do what you need to do, but don't expect help from me after not addressing my concern for more than a year. We have moved on. Good luck :)
