### ISSUE TITLE
Bug: Xcode 10 can not use InfoPlist.strings due to wrong encoding

### ISSUE THREAD

**Issue by iwan-uschka** [kelvinhokk/cordova-plugin-localization-strings#34]
Xcode seems to need UTF-8 but recognizes UTF-16. Since Xcode 10 it breaks the building process. Opening the InfoPlist.strings files within an editor to save it encoded in UTF-8 solves the issue.

**Comment by patricksebastien** [comment]
The exact error on my side:
`/.../InfoPlist.strings:-1: could not decode input file using specified encoding: Unicode (UTF-8), and the file contents appear to be encoded in Unicode (UTF-16)`

Changing the Text Encoding inside xCode to Unicode (UTF-16) fix the issue, but doesn't fix it when recreating the project (rm platform).

**Comment by patricksebastien** [comment]
Another solution:
Currently the best workaround is to opt-out of the new build system:
https://github.com/apache/cordova-ios/issues/407

**Comment by iwan-uschka** [comment]
Thx. for your last response. I am still getting the same error, using `--buildFlag="-UseModernBuildSystem=0"` didn't help. The command i am running looks like this:

    ionic build ios --developmentTeam="XYZ" --codeSignIdentity="XYZ" --provisioningProfile="XYZ" --buildFlag="-UseModernBuildSystem=0"

**Comment by tlacroix** [comment]
Any idea when the new build is going to be available thru npm/cordova? I've been patching manually and advised my team so they do the same in the meantime.

Love your plugin btw, it solved so many headaches for us being in Quebec and needing to release apps in French and English. Cheers :-)
