### ISSUE TITLE
Cannot build platform

### ISSUE THREAD

**Issue by dromansab** [kelvinhokk/cordova-plugin-localization-strings#4]
Hi, 
I've just installed this plugin and now I cannot build any platform. When I run "cordova build ios", nothing happens..
If I remove the plugin, It works properly.
I've tried to update cordova to last version (6.5.0) and neither works.

Thanks

**Comment by kelvinhokk** [comment]
will check on it.

**Comment by kelvinhokk** [comment]
I just tested cordova 6.5 on a simple hello world project and it works.  Do you have the error messages for troubleshooting?  Also does building in Xcode from the xcodeproj work (i.e. open Xcode -> select xcodeproj -> build)?

**Comment by kelvinhokk** [comment]
Thanks Athorcis, your commit is now in v1.0.1
