### ISSUE TITLE
Project revived!

### ISSUE THREAD

**Issue by rodrigograca31** [kelvinhokk/cordova-plugin-localization-strings#43]
Hi everyone.

After a long process I was able to contact Kelvin and be added as a collaborator.
Now I can maintain this project by accepting your PRs, etc.

I will start by accepting some of the easiest ones and make some progress...

**Comment by codinronan** [comment]
Great! I've been maintaining a fork but pulling this into the root would be great, will send a PR later on..

**Comment by rodrigograca31** [comment]
oh jesus! another fork full of commits and conflicts? :joy: :joy: :joy: :sob: :sob: :sob: 

I beg you to please send a "clean PR" with only what we really need.... otherwise it will be like 2 days ago, I spent hours trying to make everything work and a conflict still slipped through. :smile:

**Comment by codinronan** [comment]
This project already contains most of my work ;) only a couple other things for later versions of cordova. Believe me I'll make it as easy as I can, we are all overly busy..
