### ISSUE TITLE
creating localisation with "-" fails on android

### ISSUE THREAD

**Issue by joeldhenry** [kelvinhokk/cordova-plugin-localization-strings#58]
Using example "pt-BR.json", during building it returns this error: "cordova/platforms/android/app/src/main/res/values-pt-BR: Error: Invalid resource directory name"

Cordova-Android: 8.1.0
cordova-plugin-localization-strings: 3.2.1

**Comment by rodrigograca31** [comment]
> The language is defined by a two-letter ISO 639-1 language code, optionally followed by a two letter ISO 3166-1-alpha-2 region code (preceded by lowercase r).
https://developer.android.com/guide/topics/resources/providing-resources.html#AlternativeResources

**That means its `pt-rBR.json` and `pt-rPT.json`.**

On one of my projects I also have `pt.json` but not sure if makes a diference.... maybe test and let us know? :thinking: 

Also: https://github.com/championswimmer/android-locales
(This list shows the folder it creates... `values-pt-rBR`)

**Comment by rodrigograca31** [comment]
reading my own answer answers why I have a `pt.json` .... its the two letter ISO 639-1.
