### ISSUE TITLE
Prepare fails on iOS with "Error: Cannot read properties of undefined (reading 'project')"

### ISSUE THREAD

**Issue by pklaes** [kelvinhokk/cordova-plugin-localization-strings#72]
Prepare fails on iOS with
`Error: Cannot read properties of undefined (reading 'project')`
when an optional short name is given in config.xml as specified in [the Docs](https://cordova.apache.org/docs/en/latest/config_ref/index.html#name), e.g.
`<name short="Whatever">ACMEs cool Whatever App</name>`
This is because the optional short name is not recognized in the pattern matching in create_ios_strings.js.

Working on a pull request ...

**Comment by rodrigograca31** [comment]
can you explain why this `    var matches = config.match(new RegExp('<name>(.*?)</name>', 'i'));` wouldnt catch `ACMEs cool Whatever App` ???

**Comment by pklaes** [comment]
> can you explain why this ` var matches = config.match(new RegExp('<name>(.*?)</name>', 'i'));` wouldnt catch `ACMEs cool Whatever App` ???

Sure: The opening Tag`<name short="Whatever">` is missing the closing `>` right after `<name`.

Of course we could combine the two regex into one, something along the line `<name.*?>(.*?)</name>` , but regex are hard, better be verbose, I thought.

Thanks anyway, closing this.

**Comment by rodrigograca31** [comment]
yeah...... maybe a xml parser would be easier...... but like you said its another dependency...
