### ISSUE TITLE
How use?

### ISSUE THREAD

**Issue by cesarve77** [kelvinhokk/cordova-plugin-localization-strings#8]
Sorry for my english.

After all in readme, how use in html ?

`<div>{{HAVE_MAIL_TITLE}}</div>`

**Comment by kelvinhokk** [comment]
Hi cesarve,

This plugin does not help you with using it in html.

If you are using ionic, you can use:
https://github.com/angular-translate/angular-translate

If you are using ionic2, you can use:
https://github.com/ngx-translate/core

**Comment by cesarve77** [comment]
Ohh thanks so much
